=head1 NAME

Pod::MultiLang - multi languages in Pod

=head1 SYNOPSIS

  use Pod::MultiLang::Html;
  my $parser = Pod::MultiLang::Html->new(%opt);
  $parser->parse_from_file($infile,$outfile);

=head1 DESCRIPTION

Pod::MultiLang is a pod extesion. 
This implement JZ<><> interior sequence for write multi 
langages in sigle pod. 
one languages enclosed by J interior sequence in each paragraph. 
some heading words are translated automatically. 
note that JZ<><> is not official interior sequence, 
this is custom one.

new format for LZ<><|/> interior sequence is:,

at section part, english heading is still required.
because in many hypertext formats, link identifier is 
restricted into ASCII.

vervatim paragraphs will be joined with one blank line.

=head1 EXAMPLE

  =head1 NAME
  
  Example - Example document

  =head1 SEE ALSO
  
  L<example/somewhere>

  
  =cut

sample convertion into psedo hypertext.

 [NAME:名前]
   en) Example - Example document
   ja) Example - サンプル
 [SEE ALSO:関連項目]
   en) "somewhere" in example (linkto:example/somewhere)
   ja) example 内 "どこか" (linkto:example/somewhere)

=begin COMMENT

JZ<><<>>の外をデフォルト言語にして処理.

  content

とあったときに,

  

で処理.
でも,

  content

だけなら, 言語指定なしでそのまま

  content

で出力.

=end COMMENT

=head1 TODO

multi langual verbatim paragraph is not released.

=begin COMMENT

 default text.
 
 =begin :block
 
 =for mlpodopt lang ja
 
  japanese verbatim block.

 =for mlpodopt lang fr
 
  un bloc verbatim en francais

 =end :block

=end COMMENT

=begin COMMENT

JZ<>< *;for all langs, e.g. COPYRIGHT text >.

=end COMMENT

JZ<>< en,ja;for English and Japanese >.

=head1 SEE ALSO

L<Pod::Parser>

