=head1 NAME

Pod::MultiLang - multi languages in Pod


=head1 SYNOPSIS

  use Pod::MultiLang::Html;
  my $parser = Pod::MultiLang::Html->new(langs=>[qw(ja en)]);
  $parser->parse_from_file($infile,$outfile);

=head1 DESCRIPTION

Pod::MultiLang is a pod extesion. 
This module implements JZ<><> interior sequence for write multi 
langages in sigle pod. 
One languages enclosed by J interior sequence in each paragraph. 
Some heading words are translated automatically. 
Note that JZ<><> is not official interior sequence, 
this is custom one.


New format for LZ<><|/> interior sequence is:


 J<<< ja;
 L<< text | page /"heading J<ja; japanese heading >" >>
 >>>

At section part, English heading is still required.
Because in many hypertext formats, link identifier is 
restricted into ASCII.


Verbatim paragraphs will be joined with one blank line.


=head1 EXAMPLE

(with ja.utf8)


  =head1 NAME
  
  Example - Example document
  J<< ja;Example - サンプル >>

  =head1 SEE ALSO
  
  L<example/somewhere>
  J<<< ja;
  L<< example/somewhere J<ja;どこか> >>
  >>>
  
  =cut

sample output.


 en:NAME
 ja:名前
 en:  Example - Example document
 ja:  例 - サンプル
 en:SEE ALSO
 ja:関連項目
 en:  "somewhere" in example (linkto:example/somewhere)
 ja:  example 内 "どこか" (linkto:example/somewhere)

<!-- begin [COMMENT] behavior [ignore] -->
=head1 TODO

Multi lingual verbatim paragraph is not supported.


<!-- begin [COMMENT] behavior [ignore] -->
<!-- begin [COMMENT] behavior [ignore] -->
JZ<>< en,ja;for English and Japanese >.


=head1 UTILITY METHODS

=head2 makelinktext

 $label = $parser->makelinktext($lang,$text,$name,$sec);

if $text is specified, returns $text.
if not, returns by $name and $sec with $lang.


=head1 SEE ALSO

L<Pod::Parser>, L<Pod::MultiLang::Html>


